*** Variables ***    
&{tela_cadastro}

# TELA DE CADASTRO

...    button_registrar=//a[contains(text(),"Register")]
...    input_male=//input[@id="gender-male"]
...    input_female=//input[@id="gender-female"]
...    input_first_name=//input[@id="FirstName"]
...    input_last_name=//input[@id="LastName"]   
...    input_email=//input[@id="Email"]
...    input_senha=//input[@id="Password"]
...    input_conf_senha=//input[@id="ConfirmPassword"]      
...    button_input_registrar=//input[@id="register-button"]  